trigger:
- main

stages:
- stage: Build
  displayName: 'Build and Train Model'
  jobs:
  - job: TrainModel
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'
      displayName: 'Install Python 3.10'

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install Dependencies'

    - script: |
        python train.py
        python evaluate.py
      displayName: 'Train and Evaluate Model'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/model.pkl'
        ArtifactName: 'trained_model'
      displayName: 'Publish Trained Model'

- stage: Deploy
  displayName: 'Deploy Model to Production'
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - download: current
      artifact: trained_model

    - script: |
        echo "Deploying the trained model..."
        # Add your deployment commands here.
        # Example:
        # az ml model create --name waze-churn-model --path $(Pipeline.Workspace)/trained_model/model.pkl
        # az ml endpoint create --name waze-churn-api --file endpoint.yml
      displayName: 'Deploy Model'
